### ISSUE TITLE
Can this library can be use in standard SPI Mode

### ISSUE THREAD

**Issue by HamadyDIA** [stm32duino/MX25R6435F#5]
Hello 

Just before writing code to my STM32 i wanted to know if this library is just in Quad SPI or can work with one MISO and one MOSI.

Thanks.

**Comment by fpistm** [comment]
Hi @HamadyDIA 
as stated in the README.md:

> Arduino library to support the Quad-SPI NOR Flash memory MX25R6435F using the Quad SPI flash memories interface. Since library version 2.0.0 and [STM32 core](https://github.com/stm32duino/Arduino_Core_STM32) version 2.0.0 the OctoSPI Flash memories interface can also be used.

So not it is not managed.
